# Generated by Django 5.1.4 on 2024-12-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
